import { IoIosTime } from "react-icons/io";

function DescriptionCompo() {
  return (
    <div className=" bg-slate-700 text-white mt-5 p-5">
      <div className="text-center font-bold text-2xl my-1">Our History</div>
      <div className="flex flex-col lg:flex-row justify-evenly lg:mx-auto lg:w-3/4 items-center">
        <div className=" lg:w-3/4">
          Our company was established in 2024, where A.I. technology was at its
          peak. By building our own A.I., we can make games for our clients
          faster. Our company also has a team of experts; therefore, any raw
          data generated by A.I. can be processed further to accomplish our
          clients needs. We like playing games very much, that's why we really
          enjoy building a perfect games for our clients. We work hard, but play
          even harder.
        </div>
        <IoIosTime size={100} />
      </div>
    </div>
  );
}
export default DescriptionCompo;
