import { Inter } from "next/font/google";
import "./globals.css";
import NavbarCompo from "./navbarCompo";
import FooterCompo from "./components/footerCompo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shooting Star",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarCompo />
        {children}
        <FooterCompo />
      </body>
    </html>
  );
}
